### DISCUSSION TITLE
IntuneCD 2.2.0 beta

### DISCUSSION THREAD

**Discussion by almenscorner** [almenscorner/IntuneCD#176] [Beta talk]
How is the new `—audit` feature working for you?

is there anything that should change or be added?

**Comment by gmenziesint** [comment]
Hey,

I think it's a good idea, in practice though it's taking considerably longer to backup when using it, our backups take roughly 10 minutes to complete, with the audit feature enabled I stopped one at 30 minutes that hadn't even gone through all of our applications yet, I could easily see it taking over an hour to complete everything in our environment. Considering we run it every day we'd easily hit over the free minutes threshold for pipelines from what I can see.

**Reply by almenscorner** [reply]
There will definitely be some time added due to more requests needed. I am working to update the audit function to get all logs for the specified type upfront instead of requesting for each config. Hopefully this will speed things up a bit.

**Reply by almenscorner** [reply]
@gmenziesint In beta 3 I have changed so the audit logs are fetched in bulk, please verify if this improves performance.

**Reply by gmenziesint** [reply]
Tested this again this morning, pretty much has the same run-time as we were used to, taking roughly 11 minutes, great improvement, can see the commits per user which is great for auditing thank you! When do you expect to push this to the main branch?

**Reply by almenscorner** [reply]
Happy to hear it's now working with the expected runtime! I am looking at pushing this to main by end of this week, I am just looking for feedback if anything else should change first, for example, should the commit message be a bit shorter and only include the user and date as it otherwise can get messy?

**Reply by gmenziesint** [reply]
The commit message could be shorter even just including the date perhaps as the user is shown behind the commit message already - As seen here "Intune Backup Automation" is the git user - 
![image](https://github.com/almenscorner/IntuneCD/assets/138468674/20fd76ec-d9be-45dc-bae2-46ffa7c2dfd3)

Could the commit for the overall repo by changed back to the default git user instead of the user that has the last commit? Below in red is currently a user that performed the last commit, I'd prefer if it was the default git user provided to save some confusion.

![image](https://github.com/almenscorner/IntuneCD/assets/138468674/cb9677b7-2984-4b40-b4d4-e6312e2659a1)

**Reply by almenscorner** [reply]
I think I will just break it up in to new lines to make it more readable :)

What you need to do is in your pipeline, change the git config to just before you commit all other changes, that way the user you want will be stamped on the overall commit instead

**Reply by gmenziesint** [reply]
Still having the same problem, can you take a quick look at this? 

```
trigger:
  none
schedules:
  - cron: '0 22 * * *'
    displayName: "10PM Everyday"
    branches:
      include:
      - main
    always: true
pool:
  vmImage: ubuntu-latest
jobs:
  - job: backup_document
    displayName: Backup Intune configuration
    pool:
      vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - checkout: self
      persistCredentials: true
  #Remove existing prod-backup directory
    - task: Bash@3
      displayName: Remove existing prod-backup directory
      inputs:
        targetType: 'inline'
        script: |
          rm -rfv "$(Build.SourcesDirectory)/prod-backup"
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: false
    # Install IntuneCD
    # https://github.com/almenscorner/IntuneCD
    - task: Bash@3
      displayName: Install IntuneCD Package V2.2.0b3
      inputs:
        targetType: 'inline'
        script: |
          pip3 install IntuneCD==2.2.0b3
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
    # Backup the latest configuration, using the current directory
    - task: Bash@3
      displayName: IntuneCD backup Start
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p "$(Build.SourcesDirectory)/prod-backup"
          IntuneCD-startbackup \
          --mode=1 \
          --path "$(Build.SourcesDirectory)/prod-backup" \
          --exclude ConditionalAccess \
          --ignore-omasettings \
          --append-id \
          --autopilot=True \
          --audit
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
      env:
        TENANT_NAME: $(TENANT_NAME)
        CLIENT_ID: $(CLIENT_ID)
        CLIENT_SECRET: $(CLIENT_SECRET)
    # Commit changes and push to Azure DevOps repo
    # Set git global settings
    - task: Bash@3
      displayName: Configure Git Global Settings
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.name $(USER_NAME)
          git config --global user.email $(USER_EMAIL)
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
    - task: Bash@3
      displayName: Commit changes to Azure DevOps repo
      name: commitAndsetVariable
      inputs:
        targetType: 'inline'
        script: |
          DATEF=`date +%Y.%m.%d`
          git add --all
          # modified files in folder prod-backup
          var=$(git diff --name-only --staged -- prod-backup)
          echo "##vso[task.setVariable variable=CHANGE_DETECTED;isOutput=true;]$var"
          git commit -m "Intune config backup $DATEF"
          git push origin HEAD:main
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: false
    # Create markdown documentation
    # Install IntuneCD
    # https://github.com/almenscorner/IntuneCD
    - task: Bash@3
      displayName: Generate markdown document
      inputs:
        targetType: 'inline'
        script: |
          if [ ! -z "$(commitAndsetVariable.CHANGE_DETECTED)" ]
          then
            INTRO="Intune backup and documentation generated at $(Build.Repository.Uri) <img align=\"right\" width=\"96\" height=\"96\" src=\"./logo.png\">"
            IntuneCD-startdocumentation \
                --path="$(Build.SourcesDirectory)/prod-backup" \
                --outpath="$(Build.SourcesDirectory)/prod-as-built.md" \
                --tenantname=$TENANT_NAME \
                --intro="$INTRO" \
                #--split=Y
          else
            echo "no configuration backup change detected in the last commit, documentation will not be created"
          fi
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
      env:
        TENANT_NAME: $(TENANT_NAME)
    # Commit changes and push to repo
    - task: Bash@3
      displayName: Commit changes
      inputs:
        targetType: 'inline'
        script: |
          DATEF=`date +%Y.%m.%d`
          git add --all
          git commit -m "Intune config as-built $DATEF"
          git push origin HEAD:main
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: false
  - job: tag
    displayName: Tag repo
    dependsOn: backup_document
    condition: and(succeeded(), ne(dependencies.backup_document.outputs['commitAndsetVariable.CHANGE_DETECTED'], ''))
    pool:
      vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - checkout: self
      persistCredentials: true
    # Set git global settings
    - task: Bash@3
      displayName: Configure Git
      inputs:
        targetType: 'inline'
        script: |
          git config --global user.name $(USER_NAME)
          git config --global user.email $(USER_EMAIL)
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: true
    - task: Bash@3
      displayName: Pull origin
      inputs:
        targetType: 'inline'
        script: |
          git pull origin main
        workingDirectory: '$(Build.SourcesDirectory)'
        failOnStderr: false
    - task: PowerShell@2
      displayName: Git tag
      inputs:
        targetType: 'inline'
        script: |
          # change in configuration backup folder detected, create TAG
          $DATEF= Get-Date -format "yyyy-MM-dd_THH-mm"
          git tag -a "v$DATEF" -m "Microsoft Intune configuration snapshot $DATEF"
          git push origin "v$DATEF" *> $null # even status information goes to stderr :(
        failOnStderr: true
        pwsh: false
        workingDirectory: '$(Build.SourcesDirectory)'
  - job: publish
    displayName: Publish as-built artifacts
    dependsOn: tag
    condition: and(succeeded(), ne(dependencies.backup_document.outputs['commitAndsetVariable.CHANGE_DETECTED'], ''))
    pool:
      vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - checkout: self
      persistCredentials: true
```
