### DISCUSSION TITLE
Reducing Pipeline Runtime

### DISCUSSION THREAD

**Discussion by gmenziesint** [almenscorner/IntuneCD#216] [General]
Hey,

We're starting to see our pipeline runs taking 30 minutes plus as it's pulling all of the history for the repo. We're using Tags to tag individual backups so we can find them easily by date and time.

Would changing the checkout depth for the pipeline have an affect on the backup?

Example - 
![image](https://github.com/user-attachments/assets/9828e031-5932-44bf-9af8-edd2e25942c5)

Thanks!

**Comment by almenscorner** [comment]
If you are only creating a new tag and tagging the current state I would do a shallow depth (fetchDepth 1) as that might have an significant effect on the runtime.

**Reply by gmenziesint** [reply]
I did try this but it didn't really reduce the runtime, the fetchdepth is default 1 from what I can see from the documentation also.
Getting to the stage now where the initial pull from the repo is at about 600-700MB ish so it's fairly large now.

**Reply by almenscorner** [reply]
The checkout size of my repo is 1.3GB and it takes just under 4 minutes to do the initial pull before backup, all I do is this:

```yaml
jobs:
  - job: backup
    displayName: backup
    pool:
      vmImage: ubuntu-latest
    continueOnError: false
    steps:
    - checkout: self
      fetchDepth: 1
      persistCredentials: true
```
