### ISSUE TITLE
[BUG] git add not working as expected

### ISSUE THREAD

**Issue by dkmonaghan** [almenscorner/IntuneCD#230]
**Describe the bug**
When using `--audit`, the `git add` part of `_git_commit_changes` does not seem to add the file, and the subsequent `git commit` throws an error. If I add a `git add --all` to our pipeline after IntuneCD runs, then the file is added as expected, but the explicit `git add` within the code (to attach the commit author) fails silently. 

**To Reproduce**
Run IntuneCD in backup mode with --audit.

**Expected behavior**
A commit should be added. Instead, `git add` fails silently and the `git commit` fails as there is nothing to do.

**Screenshots**
```
[Mon Apr 28 15:28:00 2025] - Backing up Application: Adobe Photoshop
Mon Apr 28 15:28:00 2025 [INFO] [get_scope_tags_name] - Checking if scope tags are in the data.
Mon Apr 28 15:28:00 2025 [INFO] [get_scope_tags_name] - Scope tags are in the data.
Mon Apr 28 15:28:00 2025 [INFO] [get_scope_tags_name] - Scope tags: ['Default']
Mon Apr 28 15:28:00 2025 [INFO] [get_scope_tags_name] - Checking if scope tags are in the data.
Mon Apr 28 15:28:00 2025 [INFO] [process_audit_data] - Processing audit data for ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json in path ./prod-intune/Applications/Windows/.
Mon Apr 28 15:28:00 2025 [INFO] [_check_if_git_repo] - Path is set to ./prod-intune/Applications/Windows/ and file is set to ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json.
Mon Apr 28 15:28:00 2025 [INFO] [_check_if_git_repo] - Running command git command ['git', '-C', './prod-intune/Applications/Windows/', 'rev-parse', '--is-inside-work-tree'] to determine if the path is a git repo.
Mon Apr 28 15:28:00 2025 [INFO] [_check_if_git_repo] - Path is a git repo.
Mon Apr 28 15:28:00 2025 [INFO] [_git_installed] - Running command git --version to check if git is installed.
Mon Apr 28 15:28:00 2025 [INFO] [_git_installed] - Git is installed.
Mon Apr 28 15:28:00 2025 [INFO] [_configure_git] - Running command ['git', '-C', './prod-intune/Applications/Windows/', 'config', '--local', 'user.email', 'xxxxx@xxxxx.com'] to configure git user email to xxxxx@xxxxx.com.
Mon Apr 28 15:28:00 2025 [INFO] [_configure_git] - Running command ['git', '-C', './prod-intune/Applications/Windows/', 'config', '--local', 'user.name', 'xxxxx@xxxxx.com'] to configure git user name.
Mon Apr 28 15:28:00 2025 [INFO] [_git_check_modified] - Running command ['git', '-C', './prod-intune/Applications/Windows/', 'diff', '--name-only', './prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json'] to check if ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json has been modified.
Mon Apr 28 15:28:00 2025 [INFO] [_git_check_new_file] - Running command ['git', '-C', './prod-intune/Applications/Windows/', 'ls-files', '--error-unmatch', './prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json'] to check if ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json is a new file.
Mon Apr 28 15:28:00 2025 [INFO] [_git_commit_changes] - Running command ['git', '-C', './prod-intune/Applications/Windows/', 'add', './prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json'] to add ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json to the git repo.
Mon Apr 28 15:28:00 2025 [INFO] [_git_commit_changes] - Committing the changes to ./prod-intune/Applications/Windows/Adobe Photoshop_winGetApp.json.
Mon Apr 28 15:28:00 2025 [ERROR] [_git_commit_changes] - Commit was not successful, error: On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Adobe Photoshop_winGetApp.json
nothing added to co
Mon Apr 28 15:28:00 2025 [INFO] [process_audit_data] - Audit data has been processed.
```

**Run type (please complete the following information):**
 - Mode: 1
 - Client: Pipeline
 - Version: 2.4.0

**Additional context**
Our GitLab pipeline file is as follows:

```
intunecd:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  tags:
    - docker
  image: gitlab.xxxx:5555/docker/intunecd-docker
  script:
    - git checkout master
    - /intunecd/bin/IntuneCD backup -p ./prod-intune -m 1 -o json -e ManagedGooglePlay APNs --audit -v
    - git remote set-url --push origin git@xxxx:configurations/intunecd.git
    - git add --all
    - git diff-index --quiet HEAD || git -c "user.name=IntuneCD" -c "user.email=root@xxxxx" commit -m "InTune Configuration Update `date +'%Y-%m-%d %H:%M'`"
    - git push -u origin HEAD:master 
```
